<?php

/**
 * A utility plugin to remove bloat from popular plugins (admin bar items, footprints, etc.)
 *
 * Plugin name:       Remove Plugin Bloat
 * Plugin URI:        https://openwpclub.com
 * Description:       Removes admin bar items and source code footprints from popular plugins like WP Rocket, Redis Cache, etc.
 * Requires at least: 6.6
 * Requires PHP:      7.4
 * Version:           1.0.0
 * Author:            OpenWP Club
 * License:           Apache-2.0
 * Text Domain:       remove-plugin-bloat
 *
 * ============================================================================
 * HOW TO USE:
 * Comment out any section you don't need by adding // at the start of each line
 * or wrap the section in /* ... */ /* to disable it entirely.
 * ============================================================================
 */

// Prevent direct access
defined('ABSPATH') or die();

// ============================================================================
// WP ROCKET - Remove Admin Bar Item
// ============================================================================
add_action('admin_bar_menu', static function ($wp_admin_bar) {
  $wp_admin_bar->remove_node('wp-rocket');
}, 999);

// ============================================================================
// WP ROCKET - Remove HTML Comments (Footprint)
// Removes: <!-- This website is cached by WP Rocket --> etc.
// ============================================================================
add_filter('rocket_buffer', static function ($html) {
  $patterns = [
    '/<!--\s*This website is like a rocket.*?-->/is',
    '/<!--\s*Cached page generated by WP Rocket.*?-->/is',
    '/<!--\s*WP Rocket.*?-->/is',
    '/<!--\s*Debug:.*?cached.*?-->/is',
    '/<!--\s*This website is cached by WP Rocket.*?-->/is',
  ];
  return preg_replace($patterns, '', $html);
}, 999999);

// ============================================================================
// REDIS OBJECT CACHE - Remove Admin Bar Item
// ============================================================================
add_action('admin_bar_menu', static function ($wp_admin_bar) {
  $wp_admin_bar->remove_node('redis-cache');
}, 999);

// ============================================================================
// FLAVORED STARTER (FLAVOR) - Remove Admin Bar Item
// ============================================================================
// add_action('admin_bar_menu', static function ($wp_admin_bar) {
//   $wp_admin_bar->remove_node('flavor');
// }, 999);

// ============================================================================
// FLAVORED STARTER (FLAVOR) - Remove HTML Comments (Footprint)
// ============================================================================
// add_filter('starter_html_output', static function ($html) {
//   return preg_replace('/<!--\s*flavor.*?-->/is', '', $html);
// }, 999999);

// ============================================================================
// RANK MATH - Remove Admin Bar Item
// ============================================================================
add_action('admin_bar_menu', static function ($wp_admin_bar) {
  $wp_admin_bar->remove_node('rank-math');
}, 999);

// ============================================================================
// RANK MATH - Whitelabel (Remove Credit Comments from <head> and Admin Footer)
// Removes: <!-- Search Engine Optimization by Rank Math --> etc.
// ============================================================================
add_action('init', static function () {
  // Remove credit comment from <head>
  remove_action('wp_head', 'RankMath\\Head::credits', 1);
}, 999);

add_filter('rank_math/frontend/remove_credit_notice', '__return_true');

// Remove admin footer credit
add_filter('rank_math/whitelabel', '__return_true');

// ============================================================================
// RANK MATH - Remove Sitemap Credit
// Removes: <!-- XML Sitemap generated by Rank Math SEO Plugin -->
// ============================================================================
add_filter('rank_math/sitemap/remove_credit', '__return_true');

// ============================================================================
// RANK MATH - Remove Link Class from Frontend Links
// Removes: class="rank-math-link" from links
// ============================================================================
add_filter('rank_math/link/remove_class', '__return_true');

// ============================================================================
// ADD MORE PLUGINS BELOW
// Copy a section above and modify the node ID or pattern as needed
// ============================================================================
